version: '3'
services:
  mysql: # 服务名称
    image: mysql:8.3.0 # 或其它mysql版本
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+8:00
    container_name: mysql_dev # 容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root用户密码
    volumes:
      - ./data/mysql:/var/lib/mysql # 数据持久化目录，宿主机:容器
      # - ./dev.sql:/docker-entrypoint-initdb.d/dev.sql # 在容器启动时执行dev.sql脚本
    ports:
      - 3306:3306 # 指定宿主机端口与容器端口映射关系，宿主机:容器
    # restart: always # 容器随docker启动自启